import {
  OTP_INVALID_BLOCK_SECONDS,
  OTP_MAX_DURATION_SECONDS,
  OTP_RESEND_BLOCK_SECONDS,
} from "@/custom/otp"


export const OTP_INVALID_BLOCK_MS = OTP_INVALID_BLOCK_SECONDS * 1000
export const OTP_MAX_DURATION_MS = OTP_MAX_DURATION_SECONDS * 1000
export const OTP_RESEND_BLOCK_MS = OTP_RESEND_BLOCK_SECONDS * 1000