import {
  INVALID_BLOCK_SECONDS,
  MAX_DURATION_SECONDS,
  RESEND_BLOCK_SECONDS,
} from "@/custom/otp"


export const INVALID_BLOCK_MS = INVALID_BLOCK_SECONDS * 1000
export const MAX_DURATION_MS = MAX_DURATION_SECONDS * 1000
export const RESEND_BLOCK_MS = RESEND_BLOCK_SECONDS * 1000