import {
  OTP_INVALID_BLOCK_SECONDS,
  OTP_MAX_DURATION_SECONDS,
  OTP_RESEND_BLOCK_SECONDS,
} from "@/custom/otp"


export const INVALID_BLOCK_MS = OTP_INVALID_BLOCK_SECONDS * 1000
export const MAX_DURATION_MS = OTP_MAX_DURATION_SECONDS * 1000
export const RESEND_BLOCK_MS = OTP_RESEND_BLOCK_SECONDS * 1000