export const BODY_TOO_LARGE = "CONTENT:TOO_LARGE"

export const CREDENTIAL_INVALID = "CREDENTIAL:INVALID"

export const GENERIC = "GENERIC"

export const OTP_BLOCKED = "OTP:BLOCKED"
export const OTP_EXPIRED = "OTP:EXPIRED"
export const OTP_INCORRECT = "OTP:INCORRECT"
export const OTP_INVALID_COOKIE = "OTP:INVALID_COOKIE"
export const OTP_INVALID_FORMAT = "OTP:INVALID_FORMAT"
export const OTP_RESENT_NOT_ALLOWED = "OTP:RESENT_NOT_ALLOWED"
export const OTP_TOO_MANY_ATTEMPTS = "OTP:TOO_MANY_ATTEMPTS"
export const OTP_TOO_MANY_REQUESTS = "OTP:TOO_MANY_REQUESTS"

export const SERVER = "SERVER"